apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260622-190212-3w5wfpzbt2os-service
spec:
  selector:
    app: enterprise-system-20260622-190212-3w5wfpzbt2os
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
